#!/usr/bin/env python3
"""
One-time admin credential setup.

Generates:
  - A cryptographically strong random password
  - A bcrypt hash of that password  (→ ADMIN_PASSWORD_HASH)
  - A base-32 TOTP secret            (→ ADMIN_TOTP_SECRET)
  - A 32-byte JWT signing key        (→ JWT_SECRET_KEY)
  - A QR-code URL you can scan with Google Authenticator / Authy

Usage:
  pip install pyotp passlib[bcrypt]   # already in requirements.txt
  python scripts/setup_admin_auth.py

The script prints the env-var block to stdout and appends/updates
a local  .env  file (never overwrites existing ADMIN_* values unless
you pass --force).

On the VPS, set these env vars in  /etc/brocklerlaw-save/env  (or
however your systemd / docker-compose env file is managed).
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import string
import sys
from pathlib import Path

try:
    import pyotp
    from passlib.context import CryptContext
except ImportError:
    print("ERROR: pyotp and passlib are required.  Run:  pip install pyotp passlib[bcrypt]", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"

_pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")


def strong_password(length: int = 24) -> str:
    """Generate a password with uppercase, lowercase, digits, and symbols."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+[]"
    while True:
        pw = "".join(secrets.choice(alphabet) for _ in range(length))
        # Require at least one of each class
        if (
            any(c.isupper() for c in pw)
            and any(c.islower() for c in pw)
            and any(c.isdigit() for c in pw)
            and any(c in "!@#$%^&*()-_=+[]" for c in pw)
        ):
            return pw


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate admin auth credentials")
    parser.add_argument("--username", default="brockler", help="Admin username (default: brockler)")
    parser.add_argument("--issuer", default="BrocklerLaw Admin", help="TOTP issuer label")
    parser.add_argument("--force", action="store_true", help="Overwrite existing ADMIN_* vars in .env")
    args = parser.parse_args()

    # ── Generate ─────────────────────────────────────────────────────────────
    password = strong_password(24)
    password_hash = _pwd_ctx.hash(password)
    totp_secret = pyotp.random_base32()
    jwt_secret = secrets.token_hex(32)

    totp = pyotp.TOTP(totp_secret)
    provisioning_uri = totp.provisioning_uri(name=args.username, issuer_name=args.issuer)

    # ── Print ─────────────────────────────────────────────────────────────────
    print("\n" + "=" * 70)
    print("  BROCKLER LAW — NEW ADMIN CREDENTIALS")
    print("=" * 70)
    print(f"\n  Username:  {args.username}")
    print(f"  Password:  {password}")
    print()
    print("  ⚠  Copy the password NOW — it will not be shown again.")
    print()
    print("─" * 70)
    print("  Scan this URL with Google Authenticator / Authy:")
    print()
    print(f"  {provisioning_uri}")
    print()
    print("  (Or use a QR-code generator: https://www.qr-code-generator.com/)")
    print("─" * 70)
    print("\n  Add these to your .env (or VPS env file):\n")

    env_block = (
        f"ADMIN_USERNAME={args.username}\n"
        f"ADMIN_PASSWORD_HASH={password_hash}\n"
        f"ADMIN_TOTP_SECRET={totp_secret}\n"
        f"JWT_SECRET_KEY={jwt_secret}\n"
        f"JWT_ALGORITHM=HS256\n"
        f"JWT_EXPIRE_MINUTES=480\n"
    )
    print(env_block)
    print("=" * 70 + "\n")

    # ── Update .env ───────────────────────────────────────────────────────────
    _update_env_file(ENV_FILE, env_block, force=args.force)


def _update_env_file(env_path: Path, block: str, force: bool) -> None:
    """Append new auth vars to .env; skip if already present (unless --force)."""
    existing = env_path.read_text() if env_path.exists() else ""

    keys_to_set = {
        line.split("=", 1)[0].strip()
        for line in block.splitlines()
        if "=" in line
    }

    already_set = {k for k in keys_to_set if re.search(rf"^{re.escape(k)}\s*=", existing, re.MULTILINE)}

    if already_set and not force:
        print(f"  .env already contains: {', '.join(sorted(already_set))}")
        print("  Pass --force to overwrite.  No changes written.\n")
        return

    if force and already_set:
        # Remove old lines for those keys
        for key in already_set:
            existing = re.sub(rf"^{re.escape(key)}\s*=.*\n?", "", existing, flags=re.MULTILINE)

    new_content = existing.rstrip("\n") + "\n\n# Admin auth (generated by setup_admin_auth.py)\n" + block
    env_path.write_text(new_content)
    print(f"  ✓ Wrote auth vars to {env_path}\n")


if __name__ == "__main__":
    main()
